package Formularios;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import Clases.PanelRedondeado;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import javax.swing.ImageIcon;

public class frmAdministrador extends javax.swing.JFrame {

    panelAdminVendedores panelAdminVendedor = new panelAdminVendedores();
    panelAdminClientes panelAdminCliente = new panelAdminClientes();
    panelAdminRutas panelAdminRuta = new panelAdminRutas();
    
    public frmAdministrador(String nombre) {
        initComponents();
        extender();
        lbFoto.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuariologo.png")).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        lbNombreAdministrador.setText(nombre);
        panelAdminCliente.llenarTabla();
        panelAdminVendedor.llenarTabla();
        panelAdminRuta.llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelPrueba = new Clases.PanelRedondeado();
        panelRedondeado1 = new Clases.PanelRedondeado();
        lbVendedor = new javax.swing.JLabel();
        PanelPrueba1 = new Clases.PanelRedondeado();
        panelInvisible = new Clases.PanelRedondeado();
        PanelPrueba2 = new Clases.PanelRedondeado();
        panelInvisible2 = new Clases.PanelRedondeado();
        PanelPrueba8 = new Clases.PanelRedondeado();
        panelRedondeado7 = new Clases.PanelRedondeado();
        lbCliente = new javax.swing.JLabel();
        PanelPrueba10 = new Clases.PanelRedondeado();
        panelInvisible3 = new Clases.PanelRedondeado();
        PanelPrueba12 = new Clases.PanelRedondeado();
        panelRedondeado9 = new Clases.PanelRedondeado();
        lbVendedor2 = new javax.swing.JLabel();
        PanelPrueba13 = new Clases.PanelRedondeado();
        panelInvisible4 = new Clases.PanelRedondeado();
        PanelPrueba14 = new Clases.PanelRedondeado();
        panelInvisible5 = new Clases.PanelRedondeado();
        PanelPrueba9 = new Clases.PanelRedondeado();
        panelInvisible1 = new Clases.PanelRedondeado();
        lbFoto = new javax.swing.JLabel();
        lbNombreAdministrador = new javax.swing.JLabel();
        btnSalir = new Clases.PanelRedondeado();
        jLabel2 = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(760, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(50, 103, 137));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 450));

        PanelPrueba.setBackground(new java.awt.Color(50, 103, 137));
        PanelPrueba.setMaximumSize(new java.awt.Dimension(104, 40));
        PanelPrueba.setMinimumSize(new java.awt.Dimension(104, 40));

        panelRedondeado1.setRoundBottomLeft(30);
        panelRedondeado1.setRoundBottomRight(30);
        panelRedondeado1.setRoundTopLeft(30);
        panelRedondeado1.setRoundTopRight(30);
        panelRedondeado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRedondeado1MouseClicked(evt);
            }
        });

        lbVendedor.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lbVendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVendedor.setText("VENDEDORES");
        lbVendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRedondeado1Layout = new javax.swing.GroupLayout(panelRedondeado1);
        panelRedondeado1.setLayout(panelRedondeado1Layout);
        panelRedondeado1Layout.setHorizontalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        panelRedondeado1Layout.setVerticalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPruebaLayout = new javax.swing.GroupLayout(PanelPrueba);
        PanelPrueba.setLayout(PanelPruebaLayout);
        PanelPruebaLayout.setHorizontalGroup(
            PanelPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPruebaLayout.createSequentialGroup()
                .addComponent(panelRedondeado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPruebaLayout.setVerticalGroup(
            PanelPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelPrueba1.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrueba1.setMaximumSize(new java.awt.Dimension(190, 40));
        PanelPrueba1.setMinimumSize(new java.awt.Dimension(190, 40));
        PanelPrueba1.setPreferredSize(new java.awt.Dimension(190, 25));

        panelInvisible.setBackground(new java.awt.Color(50, 103, 137));
        panelInvisible.setMaximumSize(new java.awt.Dimension(190, 40));
        panelInvisible.setMinimumSize(new java.awt.Dimension(190, 40));
        panelInvisible.setPreferredSize(new java.awt.Dimension(190, 25));

        javax.swing.GroupLayout panelInvisibleLayout = new javax.swing.GroupLayout(panelInvisible);
        panelInvisible.setLayout(panelInvisibleLayout);
        panelInvisibleLayout.setHorizontalGroup(
            panelInvisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInvisibleLayout.setVerticalGroup(
            panelInvisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPrueba1Layout = new javax.swing.GroupLayout(PanelPrueba1);
        PanelPrueba1.setLayout(PanelPrueba1Layout);
        PanelPrueba1Layout.setHorizontalGroup(
            PanelPrueba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInvisible, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelPrueba1Layout.setVerticalGroup(
            PanelPrueba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrueba1Layout.createSequentialGroup()
                .addComponent(panelInvisible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelPrueba2.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrueba2.setMaximumSize(new java.awt.Dimension(190, 40));
        PanelPrueba2.setMinimumSize(new java.awt.Dimension(190, 40));
        PanelPrueba2.setPreferredSize(new java.awt.Dimension(190, 25));

        panelInvisible2.setBackground(new java.awt.Color(50, 103, 137));
        panelInvisible2.setPreferredSize(new java.awt.Dimension(190, 25));

        javax.swing.GroupLayout panelInvisible2Layout = new javax.swing.GroupLayout(panelInvisible2);
        panelInvisible2.setLayout(panelInvisible2Layout);
        panelInvisible2Layout.setHorizontalGroup(
            panelInvisible2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInvisible2Layout.setVerticalGroup(
            panelInvisible2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPrueba2Layout = new javax.swing.GroupLayout(PanelPrueba2);
        PanelPrueba2.setLayout(PanelPrueba2Layout);
        PanelPrueba2Layout.setHorizontalGroup(
            PanelPrueba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInvisible2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelPrueba2Layout.setVerticalGroup(
            PanelPrueba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrueba2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelInvisible2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelPrueba8.setBackground(new java.awt.Color(50, 103, 137));
        PanelPrueba8.setMaximumSize(new java.awt.Dimension(104, 40));
        PanelPrueba8.setMinimumSize(new java.awt.Dimension(104, 40));

        panelRedondeado7.setRoundBottomLeft(30);
        panelRedondeado7.setRoundBottomRight(30);
        panelRedondeado7.setRoundTopLeft(30);
        panelRedondeado7.setRoundTopRight(30);
        panelRedondeado7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRedondeado7MouseClicked(evt);
            }
        });

        lbCliente.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lbCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCliente.setText("CLIENTES");
        lbCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRedondeado7Layout = new javax.swing.GroupLayout(panelRedondeado7);
        panelRedondeado7.setLayout(panelRedondeado7Layout);
        panelRedondeado7Layout.setHorizontalGroup(
            panelRedondeado7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRedondeado7Layout.setVerticalGroup(
            panelRedondeado7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPrueba8Layout = new javax.swing.GroupLayout(PanelPrueba8);
        PanelPrueba8.setLayout(PanelPrueba8Layout);
        PanelPrueba8Layout.setHorizontalGroup(
            PanelPrueba8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrueba8Layout.createSequentialGroup()
                .addComponent(panelRedondeado7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPrueba8Layout.setVerticalGroup(
            PanelPrueba8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelPrueba10.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrueba10.setMaximumSize(new java.awt.Dimension(190, 40));
        PanelPrueba10.setMinimumSize(new java.awt.Dimension(190, 40));
        PanelPrueba10.setPreferredSize(new java.awt.Dimension(190, 25));

        panelInvisible3.setBackground(new java.awt.Color(50, 103, 137));
        panelInvisible3.setPreferredSize(new java.awt.Dimension(190, 25));

        javax.swing.GroupLayout panelInvisible3Layout = new javax.swing.GroupLayout(panelInvisible3);
        panelInvisible3.setLayout(panelInvisible3Layout);
        panelInvisible3Layout.setHorizontalGroup(
            panelInvisible3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInvisible3Layout.setVerticalGroup(
            panelInvisible3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPrueba10Layout = new javax.swing.GroupLayout(PanelPrueba10);
        PanelPrueba10.setLayout(PanelPrueba10Layout);
        PanelPrueba10Layout.setHorizontalGroup(
            PanelPrueba10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInvisible3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelPrueba10Layout.setVerticalGroup(
            PanelPrueba10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrueba10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelInvisible3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelPrueba12.setBackground(new java.awt.Color(50, 103, 137));
        PanelPrueba12.setMaximumSize(new java.awt.Dimension(104, 40));
        PanelPrueba12.setMinimumSize(new java.awt.Dimension(104, 40));

        panelRedondeado9.setRoundBottomLeft(30);
        panelRedondeado9.setRoundBottomRight(30);
        panelRedondeado9.setRoundTopLeft(30);
        panelRedondeado9.setRoundTopRight(30);
        panelRedondeado9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRedondeado9MouseClicked(evt);
            }
        });

        lbVendedor2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lbVendedor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVendedor2.setText("RUTAS");
        lbVendedor2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRedondeado9Layout = new javax.swing.GroupLayout(panelRedondeado9);
        panelRedondeado9.setLayout(panelRedondeado9Layout);
        panelRedondeado9Layout.setHorizontalGroup(
            panelRedondeado9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbVendedor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRedondeado9Layout.setVerticalGroup(
            panelRedondeado9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbVendedor2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPrueba12Layout = new javax.swing.GroupLayout(PanelPrueba12);
        PanelPrueba12.setLayout(PanelPrueba12Layout);
        PanelPrueba12Layout.setHorizontalGroup(
            PanelPrueba12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrueba12Layout.createSequentialGroup()
                .addComponent(panelRedondeado9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPrueba12Layout.setVerticalGroup(
            PanelPrueba12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelPrueba13.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrueba13.setMaximumSize(new java.awt.Dimension(190, 40));
        PanelPrueba13.setMinimumSize(new java.awt.Dimension(190, 40));
        PanelPrueba13.setPreferredSize(new java.awt.Dimension(190, 25));

        panelInvisible4.setBackground(new java.awt.Color(50, 103, 137));
        panelInvisible4.setMaximumSize(new java.awt.Dimension(190, 40));
        panelInvisible4.setMinimumSize(new java.awt.Dimension(190, 40));
        panelInvisible4.setPreferredSize(new java.awt.Dimension(190, 25));

        javax.swing.GroupLayout panelInvisible4Layout = new javax.swing.GroupLayout(panelInvisible4);
        panelInvisible4.setLayout(panelInvisible4Layout);
        panelInvisible4Layout.setHorizontalGroup(
            panelInvisible4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInvisible4Layout.setVerticalGroup(
            panelInvisible4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPrueba13Layout = new javax.swing.GroupLayout(PanelPrueba13);
        PanelPrueba13.setLayout(PanelPrueba13Layout);
        PanelPrueba13Layout.setHorizontalGroup(
            PanelPrueba13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInvisible4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelPrueba13Layout.setVerticalGroup(
            PanelPrueba13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrueba13Layout.createSequentialGroup()
                .addComponent(panelInvisible4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelPrueba14.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrueba14.setMaximumSize(new java.awt.Dimension(190, 40));
        PanelPrueba14.setMinimumSize(new java.awt.Dimension(190, 40));
        PanelPrueba14.setPreferredSize(new java.awt.Dimension(190, 25));

        panelInvisible5.setBackground(new java.awt.Color(50, 103, 137));
        panelInvisible5.setPreferredSize(new java.awt.Dimension(190, 25));

        javax.swing.GroupLayout panelInvisible5Layout = new javax.swing.GroupLayout(panelInvisible5);
        panelInvisible5.setLayout(panelInvisible5Layout);
        panelInvisible5Layout.setHorizontalGroup(
            panelInvisible5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInvisible5Layout.setVerticalGroup(
            panelInvisible5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPrueba14Layout = new javax.swing.GroupLayout(PanelPrueba14);
        PanelPrueba14.setLayout(PanelPrueba14Layout);
        PanelPrueba14Layout.setHorizontalGroup(
            PanelPrueba14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInvisible5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelPrueba14Layout.setVerticalGroup(
            PanelPrueba14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrueba14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelInvisible5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelPrueba9.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrueba9.setMaximumSize(new java.awt.Dimension(190, 40));
        PanelPrueba9.setMinimumSize(new java.awt.Dimension(190, 40));
        PanelPrueba9.setPreferredSize(new java.awt.Dimension(190, 25));

        panelInvisible1.setBackground(new java.awt.Color(50, 103, 137));
        panelInvisible1.setMaximumSize(new java.awt.Dimension(190, 40));
        panelInvisible1.setMinimumSize(new java.awt.Dimension(190, 40));
        panelInvisible1.setPreferredSize(new java.awt.Dimension(190, 25));

        javax.swing.GroupLayout panelInvisible1Layout = new javax.swing.GroupLayout(panelInvisible1);
        panelInvisible1.setLayout(panelInvisible1Layout);
        panelInvisible1Layout.setHorizontalGroup(
            panelInvisible1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInvisible1Layout.setVerticalGroup(
            panelInvisible1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelPrueba9Layout = new javax.swing.GroupLayout(PanelPrueba9);
        PanelPrueba9.setLayout(PanelPrueba9Layout);
        PanelPrueba9Layout.setHorizontalGroup(
            PanelPrueba9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInvisible1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelPrueba9Layout.setVerticalGroup(
            PanelPrueba9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrueba9Layout.createSequentialGroup()
                .addComponent(panelInvisible1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lbFoto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbFoto.setForeground(new java.awt.Color(255, 255, 255));
        lbFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbFoto.setMaximumSize(new java.awt.Dimension(100, 100));
        lbFoto.setMinimumSize(new java.awt.Dimension(100, 100));
        lbFoto.setPreferredSize(new java.awt.Dimension(100, 100));

        lbNombreAdministrador.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbNombreAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombreAdministrador.setText("NOMBRE");

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setMaximumSize(new java.awt.Dimension(100, 40));
        btnSalir.setMinimumSize(new java.awt.Dimension(100, 40));
        btnSalir.setRoundBottomLeft(30);
        btnSalir.setRoundBottomRight(30);
        btnSalir.setRoundTopLeft(30);
        btnSalir.setRoundTopRight(30);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cerrar Sesión");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPrueba9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrueba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrueba1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrueba2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrueba8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrueba10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrueba12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrueba13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrueba14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(lbNombreAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNombreAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPrueba2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelPrueba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelPrueba10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelPrueba8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelPrueba9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelPrueba14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelPrueba12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelPrueba13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setMaximumSize(new java.awt.Dimension(1565540, 3424540));
        contenido.setMinimumSize(new java.awt.Dimension(540, 450));
        contenido.setPreferredSize(new java.awt.Dimension(540, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frmLogin Login = new frmLogin();
        String botones[] = {"Aceptar","Cancelar"};
        int Desicion = JOptionPane.showOptionDialog (null, " ¿Estas Seguro que quieres cerrar La App?", "Seguro", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, botones, botones[0]);
        
        if (Desicion == 1)
        {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            
        }
        else 
        {
             Login.setVisible(true);
             this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void panelRedondeado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRedondeado1MouseClicked
        efectoBotones(PanelPrueba, panelInvisible, panelInvisible2, panelRedondeado1, PanelPrueba8, PanelPrueba12, panelInvisible1, panelInvisible3, panelInvisible4, panelInvisible5, panelRedondeado7, panelRedondeado9);
        mostrarPanel(panelAdminVendedor);
        
    }//GEN-LAST:event_panelRedondeado1MouseClicked

    private void panelRedondeado7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRedondeado7MouseClicked
        efectoBotones(PanelPrueba8, panelInvisible1, panelInvisible3, panelRedondeado7, PanelPrueba, PanelPrueba12, panelInvisible, panelInvisible2, panelInvisible4, panelInvisible5, panelRedondeado1, panelRedondeado9);
        mostrarPanel(panelAdminCliente);
    }//GEN-LAST:event_panelRedondeado7MouseClicked

    private void panelRedondeado9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRedondeado9MouseClicked
        efectoBotones(PanelPrueba12, panelInvisible4, panelInvisible5, panelRedondeado9, PanelPrueba, PanelPrueba8, panelInvisible, panelInvisible2, panelInvisible1, panelInvisible3, panelRedondeado1, panelRedondeado7);
        mostrarPanel(panelAdminRuta);
    }//GEN-LAST:event_panelRedondeado9MouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        frmLogin Login = new frmLogin();
        String botones[] = {"Aceptar","Cancelar"};
        int Decision = JOptionPane.showOptionDialog (null, " ¿Estas Seguro que quieres cerrar la sesión?", "Seguro", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, botones, botones[0]);

        if (Decision != 1)
        {
            this.dispose();
            Login.setVisible(true);
        }
    }//GEN-LAST:event_btnSalirMouseClicked
    
    private void efectoBotones(PanelRedondeado panel, PanelRedondeado panel1, PanelRedondeado panel2, PanelRedondeado panel3, PanelRedondeado panel4, PanelRedondeado panel5, PanelRedondeado panel6, PanelRedondeado panel7, PanelRedondeado panel8, PanelRedondeado panel9, PanelRedondeado panel10, PanelRedondeado panel11){
        panel.setBackground(new Color(255,255,255));
        panel.setRoundTopLeft(25);
        panel.setRoundBottomLeft(25);
        panel1.setRoundTopRight(25);
        panel2.setRoundBottomRight(25);
        panel3.setBackground(new Color(255,255,255));
        /*Cambiar Otros*/
        panel4.setBackground(new Color(50,103,137));
        panel4.setRoundTopLeft(0);
        panel4.setRoundBottomLeft(0);
        panel5.setBackground(new Color(50,103,137));
        panel5.setRoundTopLeft(0);
        panel5.setRoundBottomLeft(0);
        panel6.setRoundTopRight(0);
        panel7.setRoundBottomRight(0);
        panel8.setRoundTopRight(0);
        panel9.setRoundBottomRight(0);
        panel10.setBackground(new Color(240,240,240));
        panel11.setBackground(new Color(240,240,240));
    }
    
    private void mostrarPanel(JPanel p){
        p.setSize(contenido.getSize());
        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }
    
    public void extender(){
        GraphicsEnvironment env =
        GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdministrador("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Clases.PanelRedondeado PanelPrueba;
    private Clases.PanelRedondeado PanelPrueba1;
    private Clases.PanelRedondeado PanelPrueba10;
    private Clases.PanelRedondeado PanelPrueba12;
    private Clases.PanelRedondeado PanelPrueba13;
    private Clases.PanelRedondeado PanelPrueba14;
    private Clases.PanelRedondeado PanelPrueba2;
    private Clases.PanelRedondeado PanelPrueba8;
    private Clases.PanelRedondeado PanelPrueba9;
    private Clases.PanelRedondeado btnSalir;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbNombreAdministrador;
    private javax.swing.JLabel lbVendedor;
    private javax.swing.JLabel lbVendedor2;
    private Clases.PanelRedondeado panelInvisible;
    private Clases.PanelRedondeado panelInvisible1;
    private Clases.PanelRedondeado panelInvisible2;
    private Clases.PanelRedondeado panelInvisible3;
    private Clases.PanelRedondeado panelInvisible4;
    private Clases.PanelRedondeado panelInvisible5;
    private Clases.PanelRedondeado panelRedondeado1;
    private Clases.PanelRedondeado panelRedondeado7;
    private Clases.PanelRedondeado panelRedondeado9;
    // End of variables declaration//GEN-END:variables
}
