/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import Clases.Conexion;
import Clases.Rutas;
import Clases.Usuario;
import java.awt.Font;
import java.awt.Image;
import java.awt.font.TextAttribute;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author YEINER
 */
public class frmVendedor extends javax.swing.JFrame {

    Conexion cnx = new Conexion();
    ArrayList<Usuario> cliente = new ArrayList<>();
    ArrayList<Rutas> rutasfiltradas = new ArrayList<>();
    String valor = "";
    String informeOrigen = "src/Reportes/Tiquete.jrxml";
    String informeDestino = "src/Reportes/Tiquete.pdf";
    
    public frmVendedor(int documento, String nombre) {
        initComponents();
        lbAnimacion.setVisible(false);
        lbFoto.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuariologo.png")).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        lbNombreVendedor.setText(nombre);
        lbIDCliente.setVisible(false);
        Font font = lbTituloCliente.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_LOW_TWO_PIXEL);
        lbTituloCliente.setFont(font.deriveFont(attributes));
        lbTituloTiquete.setFont(font.deriveFont(attributes));
        cnx.conectar();
        rutasfiltradas.addAll(cnx.consultarRutas());
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelRedondeado5 = new Clases.PanelRedondeado();
        panelRedondeado6 = new Clases.PanelRedondeado();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbPasajero = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbDocumento = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbOrigen = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbDestino = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbFechaSalida = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbHoraSalida = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lbIDCliente = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        lbTituloCliente = new javax.swing.JLabel();
        lbTituloTiquete = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbOrigen = new javax.swing.JComboBox<>();
        cbDestino = new javax.swing.JComboBox<>();
        cbFechaSalida = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbHoraSalida = new javax.swing.JComboBox<>();
        lbFoto = new javax.swing.JLabel();
        lbNombreVendedor = new javax.swing.JLabel();
        btnSalir = new Clases.PanelRedondeado();
        jLabel2 = new javax.swing.JLabel();
        lbAnimacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 450));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelFondo.setBackground(new java.awt.Color(50, 103, 137));
        panelFondo.setMinimumSize(new java.awt.Dimension(750, 450));

        panelRedondeado5.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondeado5.setMinimumSize(new java.awt.Dimension(600, 450));

        panelRedondeado6.setBackground(new java.awt.Color(0, 159, 216));
        panelRedondeado6.setMinimumSize(new java.awt.Dimension(200, 428));
        panelRedondeado6.setRoundBottomLeft(30);
        panelRedondeado6.setRoundBottomRight(30);
        panelRedondeado6.setRoundTopLeft(30);
        panelRedondeado6.setRoundTopRight(30);

        jLabel24.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("TIQUETE");

        jLabel25.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("PASAJERO");

        lbPasajero.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbPasajero.setForeground(new java.awt.Color(255, 255, 255));
        lbPasajero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPasajero.setText("1");

        jLabel26.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("DOCUMENTO");

        lbDocumento.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbDocumento.setForeground(new java.awt.Color(255, 255, 255));
        lbDocumento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDocumento.setText("2");

        jLabel27.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("ORIGEN");

        lbOrigen.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbOrigen.setForeground(new java.awt.Color(255, 255, 255));
        lbOrigen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOrigen.setText("3");

        jLabel28.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("DESTINO");

        lbDestino.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbDestino.setForeground(new java.awt.Color(255, 255, 255));
        lbDestino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDestino.setText("4");

        jLabel29.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("FECHA");

        lbFechaSalida.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbFechaSalida.setForeground(new java.awt.Color(255, 255, 255));
        lbFechaSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFechaSalida.setText("5");

        jLabel30.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("HORA SALIDA");

        lbHoraSalida.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbHoraSalida.setForeground(new java.awt.Color(255, 255, 255));
        lbHoraSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHoraSalida.setText("6");

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("VALOR:");

        lbValor.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbValor.setForeground(new java.awt.Color(255, 255, 255));
        lbValor.setText("200.000");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelRedondeado6Layout = new javax.swing.GroupLayout(panelRedondeado6);
        panelRedondeado6.setLayout(panelRedondeado6Layout);
        panelRedondeado6Layout.setHorizontalGroup(
            panelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRedondeado6Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jSeparator4)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPasajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHoraSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbIDCliente)))
                .addContainerGap())
        );
        panelRedondeado6Layout.setVerticalGroup(
            panelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(1, 1, 1)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPasajero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDocumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbOrigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFechaSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHoraSalida)
                .addGap(36, 36, 36)
                .addGroup(panelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(lbValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbIDCliente)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel5.setText("DOCUMENTO");

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel7.setText("NOMBRE");

        txtNombre.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel8.setText("APELLIDO");

        txtApellido.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel12.setText("TELÉFONO");

        txtTelefono.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel14.setText("CONTRASEÑA");

        txtContrasena.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel16.setText("EMAIL");

        txtEmail.setEnabled(false);

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setText("Imprimir");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbTituloCliente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbTituloCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloCliente.setText("Consultar Cliente");

        lbTituloTiquete.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbTituloTiquete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloTiquete.setText("Crear Tiquete");

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ORIGEN");

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DESTINO");

        jLabel17.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("FECHA SALIDA");

        cbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciudad", "Santa Marta", "Barranquilla", "Cartagena", "Valledupar" }));
        cbOrigen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbOrigen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOrigenItemStateChanged(evt);
            }
        });

        cbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciudad", "Santa Marta", "Barranquilla", "Cartagena", "Valledupar" }));
        cbDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDestinoItemStateChanged(evt);
            }
        });

        cbFechaSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbFechaSalida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFechaSalidaItemStateChanged(evt);
            }
        });
        cbFechaSalida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbFechaSalidaFocusLost(evt);
            }
        });
        cbFechaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbFechaSalidaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbFechaSalidaMouseExited(evt);
            }
        });
        cbFechaSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbFechaSalidaKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("HORA");

        cbHoraSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbHoraSalida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbHoraSalidaItemStateChanged(evt);
            }
        });
        cbHoraSalida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbHoraSalidaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelRedondeado5Layout = new javax.swing.GroupLayout(panelRedondeado5);
        panelRedondeado5.setLayout(panelRedondeado5Layout);
        panelRedondeado5Layout.setHorizontalGroup(
            panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado5Layout.createSequentialGroup()
                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedondeado5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(lbTituloCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))
                                    .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                        .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRedondeado5Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmail)
                                            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(jLabel14)))
                            .addComponent(lbTituloTiquete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelRedondeado5Layout.createSequentialGroup()
                        .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jButton1))
                            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbFechaSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(cbOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbHoraSalida, 0, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(panelRedondeado6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRedondeado5Layout.setVerticalGroup(
            panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRedondeado5Layout.createSequentialGroup()
                        .addComponent(lbTituloCliente)
                        .addGap(28, 28, 28)
                        .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado5Layout.createSequentialGroup()
                                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTituloTiquete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(panelRedondeado6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lbFoto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbFoto.setForeground(new java.awt.Color(255, 255, 255));
        lbFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbFoto.setMaximumSize(new java.awt.Dimension(100, 100));
        lbFoto.setMinimumSize(new java.awt.Dimension(100, 100));
        lbFoto.setPreferredSize(new java.awt.Dimension(100, 100));

        lbNombreVendedor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbNombreVendedor.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreVendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombreVendedor.setText("NOMBRE");

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setMaximumSize(new java.awt.Dimension(100, 40));
        btnSalir.setMinimumSize(new java.awt.Dimension(100, 40));
        btnSalir.setRoundBottomLeft(30);
        btnSalir.setRoundBottomRight(30);
        btnSalir.setRoundTopLeft(30);
        btnSalir.setRoundTopRight(30);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cerrar Sesión");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNombreVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(panelRedondeado5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNombreVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        lbAnimacion.setBackground(new java.awt.Color(255, 255, 255));
        lbAnimacion.setForeground(new java.awt.Color(255, 255, 255));
        lbAnimacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAnimacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/animacion.gif"))); // NOI18N
        lbAnimacion.setMaximumSize(new java.awt.Dimension(750, 450));
        lbAnimacion.setMinimumSize(new java.awt.Dimension(750, 450));
        lbAnimacion.setPreferredSize(new java.awt.Dimension(750, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbAnimacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbAnimacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frmLogin Login = new frmLogin();
        String botones[] = {"Aceptar","Cancelar"};
        int Decision = JOptionPane.showOptionDialog (null, " ¿Estas Seguro que quieres cerrar La App?", "Seguro", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, botones, botones[0]);
        
        if (Decision == 1)
        {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            
        }
        else 
        {
            Login.setVisible(true);
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        limpiar();
        if (txtDocumento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo documento está vacío.", "Error", 0);
        }else{
            deshabilitar();
            cliente.addAll(cnx.consultarUsuario("Cliente"));
            for (int i = 0; i < cliente.size(); i++) {
                if (cliente.get(i).getDocumento().equals(txtDocumento.getText())) {
                    lbPasajero.setText(cliente.get(i).getNombre() + " " + cliente.get(i).getApellido());
                    lbDocumento.setText(cliente.get(i).getDocumento());
                    txtNombre.setText(cliente.get(i).getNombre());
                    txtApellido.setText(cliente.get(i).getApellido());
                    txtEmail.setText(cliente.get(i).getEmail());
                    txtTelefono.setText(cliente.get(i).getTelefono());
                    txtContrasena.setText(cliente.get(i).getContrasena());
                    lbIDCliente.setText("" + cliente.get(i).getId_usuario());
                }
            }
            if (lbPasajero.getText().equals("")) {
                habilitar();
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (!txtDocumento.getText().equals("") && !txtNombre.getText().equals("") && !txtApellido.getText().equals("") && !txtEmail.getText().equals("") && !txtTelefono.getText().equals("") && !txtContrasena.getText().equals("")) {
            boolean correcto = cnx.ingresarUSuario(txtDocumento.getText(), txtNombre.getText() + " " + txtApellido.getText(), txtContrasena.getText(), txtTelefono.getText(), txtEmail.getText(),txtDocumento.getText() ,"Cliente");
            if (correcto){
                JOptionPane.showMessageDialog(null, "Usuario Registrado con éxito.");
                deshabilitar();
                limpiar();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Hay uno o más campos vacios.", "Error", 0);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        frmLogin Login = new frmLogin();
        String botones[] = {"Aceptar","Cancelar"};
        int Decision = JOptionPane.showOptionDialog (null, " ¿Estas Seguro que quieres cerrar la sesión?", "Seguro", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, botones, botones[0]);

        if (Decision != 1)
        {
            this.dispose();
            Login.setVisible(true);
        }
    }//GEN-LAST:event_btnSalirMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lbHoraSalida.setText(cbHoraSalida.getSelectedItem().toString());
        lbFechaSalida.setText(cbFechaSalida.getSelectedItem().toString());
        ejecutarAnimacion();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbOrigenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOrigenItemStateChanged
        if (cbOrigen.getSelectedIndex() > 0 && cbDestino.getSelectedIndex() > 0) {
            cbFechaSalida.removeAllItems();
            cbHoraSalida.removeAllItems();
            horaFechaViaje();
            if (cbOrigen.getSelectedIndex() != cbDestino.getSelectedIndex()) {
                lbOrigen.setText(cbOrigen.getSelectedItem().toString());
                lbDestino.setText(cbDestino.getSelectedItem().toString());
                lbValor.setText(valor);
            }else{
                cbOrigen.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "El origen y destino no pueden ser iguales.", "Error", 0);
            }
        }
    }//GEN-LAST:event_cbOrigenItemStateChanged

    private void cbDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDestinoItemStateChanged
        if (cbOrigen.getSelectedIndex() > 0 && cbDestino.getSelectedIndex() > 0) {
            cbFechaSalida.removeAllItems();
            cbHoraSalida.removeAllItems();
            horaFechaViaje();
            if (cbOrigen.getSelectedIndex() != cbDestino.getSelectedIndex()) {
                lbOrigen.setText(cbOrigen.getSelectedItem().toString());
                lbDestino.setText(cbDestino.getSelectedItem().toString());
                
                lbValor.setText(valor);
            }else{
                cbDestino.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "El destino y origen no pueden ser iguales.", "Error", 0);
            }
        }
    }//GEN-LAST:event_cbDestinoItemStateChanged

    private void cbHoraSalidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbHoraSalidaItemStateChanged
        
    }//GEN-LAST:event_cbHoraSalidaItemStateChanged

    private void cbFechaSalidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFechaSalidaItemStateChanged
        
    }//GEN-LAST:event_cbFechaSalidaItemStateChanged

    private void cbFechaSalidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbFechaSalidaKeyPressed
        
    }//GEN-LAST:event_cbFechaSalidaKeyPressed

    private void cbFechaSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFechaSalidaMouseClicked
        
    }//GEN-LAST:event_cbFechaSalidaMouseClicked

    private void cbFechaSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFechaSalidaMouseExited
        
    }//GEN-LAST:event_cbFechaSalidaMouseExited

    private void cbFechaSalidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbFechaSalidaFocusLost
        lbHoraSalida.setText(cbHoraSalida.getSelectedItem().toString());
        lbFechaSalida.setText(cbFechaSalida.getSelectedItem().toString());
    }//GEN-LAST:event_cbFechaSalidaFocusLost

    private void cbHoraSalidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbHoraSalidaFocusLost
        lbHoraSalida.setText(cbHoraSalida.getSelectedItem().toString());
        lbFechaSalida.setText(cbFechaSalida.getSelectedItem().toString());
    }//GEN-LAST:event_cbHoraSalidaFocusLost
    
    public void horaFechaViaje(){
        for (Rutas rutas : rutasfiltradas) {
            if (rutas.getOrigen().equals(cbOrigen.getSelectedItem().toString())) {
                if (rutas.getDestino().equals(cbDestino.getSelectedItem().toString())) {
                    cbFechaSalida.addItem(rutas.getFechaViaje().toString());
                    cbHoraSalida.addItem("" + rutas.getHoraViaje());
                    valor = rutas.getCosto();
                }
            }
        }
    }
    
    public void quitarAnimacion(){
        panelFondo.setVisible(true);
        limpiar();
        lbAnimacion.setVisible(false);
    }
    
    public void ejecutarAnimacion(){
        ScheduledExecutorService service = Executors.newSingleThreadScheduledExecutor();
        service.schedule(this::generarReporte, 1, TimeUnit.SECONDS);
        service.schedule(this::quitarAnimacion, 2, TimeUnit.SECONDS);
        cnx.crearTiquete(lbOrigen.getText(), lbDestino.getText(), lbValor.getText(), lbFechaSalida.getText(), lbHoraSalida.getText(), Integer.parseInt(lbIDCliente.getText()));
        panelFondo.setVisible(false);
        lbAnimacion.setVisible(true);
        
    }
    
    public void generarReporte(){
        try {
            JasperReport jasperReport = JasperCompileManager.compileReport(informeOrigen);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,null, cnx.conectar());
            JasperExportManager.exportReportToPdfFile(jasperPrint, informeDestino);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            System.err.println(ex.getMessage());
        }
    }
    
    public void deshabilitar(){
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtEmail.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtContrasena.setEnabled(false);
        btnRegistrar.setEnabled(false);
    }
    
    public void habilitar(){
        txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
        txtEmail.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtContrasena.setEnabled(true);
        btnRegistrar.setEnabled(true);
    }
    
    public void limpiar(){
        txtNombre.setText("");
        txtApellido.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        txtContrasena.setText("");
        lbPasajero.setText("");
        lbDocumento.setText("");
        lbOrigen.setText("");
        lbDestino.setText("");
        lbFechaSalida.setText("");
        lbHoraSalida.setText("");
        lbValor.setText("");
        cbOrigen.setSelectedIndex(0);
        cbDestino.setSelectedIndex(0);
        cbFechaSalida.removeAllItems();
        cbHoraSalida.removeAllItems();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVendedor(0, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private Clases.PanelRedondeado btnSalir;
    private javax.swing.JComboBox<String> cbDestino;
    private javax.swing.JComboBox<String> cbFechaSalida;
    private javax.swing.JComboBox<String> cbHoraSalida;
    private javax.swing.JComboBox<String> cbOrigen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbAnimacion;
    private javax.swing.JLabel lbDestino;
    private javax.swing.JLabel lbDocumento;
    private javax.swing.JLabel lbFechaSalida;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbHoraSalida;
    private javax.swing.JLabel lbIDCliente;
    private javax.swing.JLabel lbNombreVendedor;
    private javax.swing.JLabel lbOrigen;
    private javax.swing.JLabel lbPasajero;
    private javax.swing.JLabel lbTituloCliente;
    private javax.swing.JLabel lbTituloTiquete;
    private javax.swing.JLabel lbValor;
    private javax.swing.JPanel panelFondo;
    private Clases.PanelRedondeado panelRedondeado5;
    private Clases.PanelRedondeado panelRedondeado6;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
