/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Conexion;
import Clases.Rutas;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Time;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import table.TableCustom;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author YEINER
 */
public class panelAdminRutas extends javax.swing.JPanel {

    /**
     * Creates new form panelAdminRutas
     */
    TableRowSorter trs;
    Conexion cnx = new Conexion();
    ArrayList<Rutas> rutas = new ArrayList<>();
    DefaultTableModel tabla;
    String [] ruta = new String [8];
    Date hora;
    Calendar calendar;
    SpinnerDateModel sm;
    JSpinner.DateEditor de;
    int indiceTabla, indiceArray;
    public panelAdminRutas() {
        initComponents();
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        tabla = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };
        txtHoraViaje.setEditable(false);
        setearHora(0, 0, 0);
        tabla.addColumn("ID");
        tabla.addColumn("Salida");
        tabla.addColumn("Destino");
        tabla.addColumn("Tiempo Aproximado");
        tabla.addColumn("Costo");
        tabla.addColumn("Fecha Viaje");
        tabla.addColumn("Hora Viaje");
        tabla.addColumn("ID Bus");
        tblRuta.setModel(tabla);
        
    }
    
    public void llenarTabla(){
        cnx.conectar();
        limpiarTabla();
        rutas.addAll(cnx.consultarRutas());
        for (int i = 0; i < rutas.size(); i++) {
            ruta[0] = "" + rutas.get(i).getIdRutas();
            ruta[1] = rutas.get(i).getOrigen();
            ruta[2] = rutas.get(i).getDestino();
            ruta[3] = "" + rutas.get(i).getTiempoAproximado();
            ruta[4] = rutas.get(i).getCosto();
            ruta[5] = "" + rutas.get(i).getFechaViaje();
            ruta[6] = "" + rutas.get(i).getHoraViaje();
            ruta[7] = "" + rutas.get(i).getIdBus();
            tabla.addRow(ruta);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timePicker1 = new com.raven.swing.TimePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRuta = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        panelCrear = new Clases.PanelRedondeado();
        btnCrear = new javax.swing.JButton();
        panelEditar = new Clases.PanelRedondeado();
        btnEditar = new javax.swing.JButton();
        panelEliminar = new Clases.PanelRedondeado();
        btnEliminar = new javax.swing.JButton();
        txtSalida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinnerTiempo = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        txtHoraViaje = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIDBus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtFechaViaje = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        timePicker1.setForeground(new java.awt.Color(50, 103, 137));
        timePicker1.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1565540, 3424540));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setPreferredSize(new java.awt.Dimension(800, 450));

        tblRuta.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        tblRuta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Salida", "Destino", "Tiempo Aproximado", "Costo", "ID Bus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRuta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblRuta.setOpaque(false);
        tblRuta.getTableHeader().setResizingAllowed(false);
        tblRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRutaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRuta);
        if (tblRuta.getColumnModel().getColumnCount() > 0) {
            tblRuta.getColumnModel().getColumn(0).setPreferredWidth(35);
            tblRuta.getColumnModel().getColumn(1).setPreferredWidth(55);
            tblRuta.getColumnModel().getColumn(2).setPreferredWidth(55);
            tblRuta.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblRuta.getColumnModel().getColumn(4).setPreferredWidth(55);
            tblRuta.getColumnModel().getColumn(5).setPreferredWidth(35);
        }

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        panelCrear.setBackground(new java.awt.Color(153, 255, 153));
        panelCrear.setMaximumSize(new java.awt.Dimension(100, 30));
        panelCrear.setMinimumSize(new java.awt.Dimension(100, 30));
        panelCrear.setPreferredSize(new java.awt.Dimension(100, 30));
        panelCrear.setRoundBottomLeft(30);
        panelCrear.setRoundBottomRight(30);
        panelCrear.setRoundTopLeft(30);
        panelCrear.setRoundTopRight(30);

        btnCrear.setBackground(new java.awt.Color(102, 255, 102));
        btnCrear.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnCrear.setText("CREAR");
        btnCrear.setContentAreaFilled(false);
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelEditar.setBackground(new java.awt.Color(50, 103, 137));
        panelEditar.setMaximumSize(new java.awt.Dimension(100, 30));
        panelEditar.setMinimumSize(new java.awt.Dimension(100, 30));
        panelEditar.setPreferredSize(new java.awt.Dimension(100, 30));
        panelEditar.setRoundBottomLeft(30);
        panelEditar.setRoundBottomRight(30);
        panelEditar.setRoundTopLeft(30);
        panelEditar.setRoundTopRight(30);

        btnEditar.setBackground(new java.awt.Color(102, 255, 102));
        btnEditar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelEliminar.setBackground(new java.awt.Color(255, 51, 51));
        panelEliminar.setMaximumSize(new java.awt.Dimension(100, 30));
        panelEliminar.setMinimumSize(new java.awt.Dimension(100, 30));
        panelEliminar.setRoundBottomLeft(30);
        panelEliminar.setRoundBottomRight(30);
        panelEliminar.setRoundTopLeft(30);
        panelEliminar.setRoundTopRight(30);

        btnEliminar.setBackground(new java.awt.Color(102, 255, 102));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel5.setText("Salida:");

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel6.setText("Destino:");

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel7.setText("Tiempo Aproximado:");

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setText("Costo:");

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel9.setText("Fecha Viaje:");

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 11)); // NOI18N
        jLabel4.setText("Filtrar:");

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel10.setText("Hora Viaje:");

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setText("ID Bus:");

        jButton1.setText("...");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        txtFechaViaje.setDateFormatString("yyyy/MM/dd");

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RUTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFechaViaje, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtSalida))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(spinnerTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtHoraViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIDBus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(panelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spinnerTiempo)
                                .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaViaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHoraViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIDBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        txtBusqueda.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter(txtBusqueda.getText()));
            }
        });
        trs = new TableRowSorter(tabla);
        tblRuta.setRowSorter(trs);
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void tblRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRutaMouseClicked
        indiceTabla = Integer.parseInt(tabla.getValueAt(tblRuta.getSelectedRow(), 0).toString()) - 1; 
        for (int i = 0; i < rutas.size(); i++) {
            if (indiceTabla + 1 == rutas.get(i).getIdRutas()) {
                indiceArray = i;
            }
        }
        txtSalida.setText(rutas.get(indiceArray).getOrigen());
        txtDestino.setText(rutas.get(indiceArray).getDestino());
        setearHora(rutas.get(indiceArray).getTiempoAproximado().getHours(),rutas.get(indiceArray).getTiempoAproximado().getMinutes(),rutas.get(indiceArray).getTiempoAproximado().getSeconds());
        txtCosto.setText(rutas.get(indiceArray).getCosto());
        txtFechaViaje.setDate(rutas.get(indiceArray).getFechaViaje());
        txtHoraViaje.setText("" + rutas.get(indiceArray).getHoraViaje());
        txtIDBus.setText("" + rutas.get(indiceArray).getIdBus());
    }//GEN-LAST:event_tblRutaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        timePicker1.setDisplayText(txtHoraViaje);
        timePicker1.showPopup(this, 100, 100);
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        java.sql.Date fechasql= new java.sql.Date(txtFechaViaje.getDate().getYear(),txtFechaViaje.getDate().getMonth(),txtFechaViaje.getDate().getDate());
        if (cnx.editarRuta(rutas.get(indiceArray).getIdRutas(), txtSalida.getText(), txtDestino.getText(), Time.valueOf(obtenerTiempo(spinnerTiempo.getModel().getValue().toString())), txtCosto.getText(), fechasql,timePicker1.getSelectedTime(), Integer.parseInt(txtIDBus.getText()))) {
            JOptionPane.showMessageDialog(this, "Ruta modificada exitosamente.");
            llenarTabla();
        }else{
            JOptionPane.showMessageDialog(this, "La ruta no pudo ser modificada.", "Error", 0);
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (cnx.eliminarRuta(rutas.get(indiceArray).getIdRutas())) {
            JOptionPane.showMessageDialog(this, "Ruta eliminada exitosamente.");
            llenarTabla();
        }else{
            JOptionPane.showMessageDialog(this, "La ruta no pudo ser eliminada.", "Error", 0);
        }
        
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        java.sql.Date fechasql= new java.sql.Date(txtFechaViaje.getDate().getYear(),txtFechaViaje.getDate().getMonth(),txtFechaViaje.getDate().getDate());
        if (cnx.crearRuta(txtSalida.getText(), txtDestino.getText(), Time.valueOf(obtenerTiempo(spinnerTiempo.getModel().getValue().toString())), txtCosto.getText(), fechasql,timePicker1.getSelectedTime(), Integer.parseInt(txtIDBus.getText()))) {
            JOptionPane.showMessageDialog(this, "Ruta creada exitosamente.");
            llenarTabla();
        }else{
            JOptionPane.showMessageDialog(this, "La ruta no pudo ser creada.", "Error", 0);
        }
    }//GEN-LAST:event_btnCrearMouseClicked
    
    public void limpiarTabla(){
        rutas.removeAll(rutas);
        for (int i = 0; i < tblRuta.getRowCount(); i++) {
            tabla.removeRow(i);
            i-=1;
        }
    }
    
    public void setearHora(int horas, int minutos, int segundos){
        calendar = Calendar.getInstance();
        calendar.set(Calendar.HOUR_OF_DAY, horas);
        calendar.set(Calendar.MINUTE, minutos);
        calendar.set(Calendar.SECOND, segundos);
        hora = calendar.getTime();
        sm = new SpinnerDateModel(hora, null, null, Calendar.HOUR_OF_DAY);
        spinnerTiempo.setModel(sm);
        de = new JSpinner.DateEditor(spinnerTiempo, "HH:mm:ss");
        spinnerTiempo.setEditor(de);
    }
    
    public String obtenerTiempo(String horaS) {
        String[] horaStr = horaS.split(" ");  // separo el string ingresado
        String horaAproximada = horaStr[3];
        return horaAproximada;      // devuelve el número de espacios de la cadena introducida
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private Clases.PanelRedondeado panelCrear;
    private Clases.PanelRedondeado panelEditar;
    private Clases.PanelRedondeado panelEliminar;
    private javax.swing.JSpinner spinnerTiempo;
    private javax.swing.JTable tblRuta;
    private com.raven.swing.TimePicker timePicker1;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDestino;
    private com.toedter.calendar.JDateChooser txtFechaViaje;
    private javax.swing.JTextField txtHoraViaje;
    private javax.swing.JTextField txtIDBus;
    private javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}
